maintainer       "Ross Cooperman"
maintainer_email "cooperman@gmail.com"
license          "Apache 2.0"
description      "Installs/Configures MySQL client libraries and headers"
version          "0.0.1"
